### PR TITLE
Add a script to update the list of releases 

### PR DESCRIPTION
**Pull request by MoonlightSentinel**
The script enables automatic updates to the docker image (instead of manual changes via PR's).

---

Extracted from #17 with minor tweaks to make the script more robust / versatile

CC @PetarKirov

### CODE REVIEW

**Comment by MoonlightSentinel** [comment]
> ```
> 301 Nov 29 17:36 compiler-versions.lst
> ```
> 
> And the following modifications to the Dockerfile:
> 
> ```
> FROM alpine as dmd-fetcher
> 
> RUN apk add bash curl xz gnupg
> 
> RUN curl -fsSL https://dlang.org/install.sh > install.sh
> 
> COPY compiler-versions.lst .
> 
> RUN cat compiler-versions.lst | while read version; \
>   do \
>     echo "Downloading 'dmd-${version}'"; \
>     bash install.sh "dmd-${version}"; \
>   done
> ```

The changes seem to be similar to the first commit. I assume that `compiler-versions.lst` was a fixed list of revisions?

**Comment by PetarKirov** [comment]
> Was compiler-versions.lst a fixed list of revisions?

It looks exactly the same as yours (each version on a separate line) +/- some differences in versions (I had `2.098.0` in mine, since the `2.098.1` was not yet released) ;)

**Comment by MoonlightSentinel** [comment]
The current implementation limits the list to the last 40 releases to keep the image at a reasonable size. Or would it be better to include all versions since `2.060` as done before?

**Review by PetarKirov — APPROVED** [review]

**Comment by PetarKirov** [comment]
> The current implementation limits the list to the last 40 releases to keep the image at a reasonable size.

The problem is not so much about the image size (though at over 5GB it certainly is not ideal), but that the request time scales linearly with the number of compilers and is much more likely to timeout.

I am hoping in the not too distant future to rework the architecture of the whole tour to to solve this other related problems.

**Pull request merged**
